version: 2
jobs:
  build:
    docker: 
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: 
        name: install dependencies
        command: |
          apt-get httpd
      - run: python success.py
