version: 2
jobs:
  build:
    docker: 
#     - image: circleci/python:3.6.1
      - image: httpd:latest
    steps:
      - checkout
      - run: ls /usr/local/apache2/htdocs
#     - run: /usr/bin/sudo apt-get install curl
      - run: wget localhost:8080
      - run: python success.py
