version: 2
jobs:
  build:
    docker: 
#     - image: circleci/python:3.6.1
      - image: httpd:latest
    steps:
      - checkout
      - run: cat /usr/local/apache2/htdocs/index.html
      - run: ip addr show
      - run: apt-get update
      - run: apt-get -y install curl
      - run: ps -ef | grep httpd
      - run: httpd 
      - run: sleep 5
      - run: ps -ef | grep httpd
      - run: curl localhost
