version: 2
jobs:
  build:
    docker: 
      - image: circleci/python:3.6.1
      - image: httpd:latest
    steps:
      - checkout
      - run: ls /usr/local/apache2/htdocs
      - run: curl localhost:8080
      - run: python success.py
